### ISSUE TITLE
`GLIBC_2.16' not found

### ISSUE THREAD

**Issue by Shlpeng** [aliyun/aliyun-emapreduce-datasources#505]
java.lang.UnsatisfiedLinkError: /tmp/libjboot-0c06b2b9c9be3e90_20200909_114345.so: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /tmp/libjboot-0c06b2b9c9be3e90_20200909_114345.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.alibaba.jboot.NativeCodeLoader.loadLibrary(NativeCodeLoader.java:102)
	at com.alibaba.jboot.NativeCodeLoader.loadLibrary(NativeCodeLoader.java:59)
	at com.alibaba.jboot.NativeCodeLoader.load(NativeCodeLoader.java:39)
	at com.alibaba.jboot.JbootNative.<clinit>(JbootNative.java:19)
	at shade.com.aliyun.emr.fs.common.AbstractJindoFileSystem.initialize(AbstractJindoFileSystem.java:70)
	at shade.com.aliyun.emr.fs.oss.JindoOssFileSystem.initialize(JindoOssFileSystem.java:76)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at shade.com.aliyun.emr.jindo.distcp.CopyCommitter.<init>(CopyCommitter.java:86)
	at shade.com.aliyun.emr.jindo.distcp.CopyOutputFormat.getOutputCommitter(CopyOutputFormat.java:12)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$2.call(MRAppMaster.java:516)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$2.call(MRAppMaster.java:498)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.callWithJobClassLoader(MRAppMaster.java:1593)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.createOutputCommitter(MRAppMaster.java:498)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.serviceInit(MRAppMaster.java:284)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:163)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$5.run(MRAppMaster.java:1551)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.initAndStartAppMaster(MRAppMaster.java:1548)
	at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1481)

**Comment by Shlpeng** [comment]
已经通过strings /lib64/libc.so.6 |grep GLIBC_查看结果：
有GLIBC_2.16

**Comment by Shlpeng** [comment]
> 已经通过strings /lib64/libc.so.6 |grep GLIBC_查看结果：
> 有GLIBC_2.16

但只是客户端的，就是hadoop执行命令的那台机器，集群的机器并不是GLIBC_2.16

**Comment by uncleGen** [comment]
cc @drankye

**Comment by wsu13** [comment]
@Shlpeng You can use this jar [jindofs-3.0.0-lite.jar](https://smartdata-binary.oss-cn-shanghai.aliyuncs.com/jindofs-3.0.0-lite.jar)  that is pure java implementation.

**Comment by schahaha** [comment]
> @Shlpeng You can use this jar [jindofs-3.0.0-lite.jar](https://smartdata-binary.oss-cn-shanghai.aliyuncs.com/jindofs-3.0.0-lite.jar) that is pure java implementation.

It takes no effect  on my app. 

> D:\tmp\libjboot-951b3084db614a3b_20200923_131955.so: Can't load this .dll (machine code=0x58b) on a AMD 64-bit platform

**Comment by wsu13** [comment]
> > @Shlpeng You can use this jar [jindofs-3.0.0-lite.jar](https://smartdata-binary.oss-cn-shanghai.aliyuncs.com/jindofs-3.0.0-lite.jar) that is pure java implementation.
> 
> It takes no effect on my app.
> 
> > D:\tmp\libjboot-951b3084db614a3b_20200923_131955.so: Can't load this .dll (machine code=0x58b) on a AMD 64-bit platform

you have to remove the jindofs-sdk-*.jar first, only after that then you can put  jindofs-3.0.0-lite.jar in your classpath.

**Comment by schahaha** [comment]
> > > @Shlpeng You can use this jar [jindofs-3.0.0-lite.jar](https://smartdata-binary.oss-cn-shanghai.aliyuncs.com/jindofs-3.0.0-lite.jar) that is pure java implementation.
> > 
> > 
> > It takes no effect on my app.
> > > D:\tmp\libjboot-951b3084db614a3b_20200923_131955.so: Can't load this .dll (machine code=0x58b) on a AMD 64-bit platform
> 
> you have to remove the jindofs-sdk-*.jar first, only after that then you can put jindofs-3.0.0-lite.jar in your classpath.

Thanks.  I downloaded the above jar package,  and stored it in the local maven repo by mvn install:install-file, and configure dependency in the pom.xml file.  But It still take no effect.

**Comment by schahaha** [comment]
and there is no another place to reference the dependency .

**Comment by schahaha** [comment]
> > > > @Shlpeng You can use this jar [jindofs-3.0.0-lite.jar](https://smartdata-binary.oss-cn-shanghai.aliyuncs.com/jindofs-3.0.0-lite.jar) that is pure java implementation.
> > > 
> > > 
> > > It takes no effect on my app.
> > > > D:\tmp\libjboot-951b3084db614a3b_20200923_131955.so: Can't load this .dll (machine code=0x58b) on a AMD 64-bit platform
> > 
> > 
> > you have to remove the jindofs-sdk-*.jar first, only after that then you can put jindofs-3.0.0-lite.jar in your classpath.
> 
> Thanks. I downloaded the above jar package, and stored it in the local maven repo by mvn install:install-file, and configure dependency in the pom.xml file. But It still take no effect.

problem resovled , it's all due to the local  maven cache.

**Comment by uncleGen** [comment]
I will close this issue, and thanks @wsu13
